### ISSUE TITLE
Error -IA/Buena_Vista - Aja

### ISSUE THREAD

**Issue by public-safety-lab** [public-safety-lab/JDI#5]
[ec2-user@ip-172-31-85-13 Buena_Vista]$ python Buena_Vista.py
********** SCRAPE INFORMATION **********

Today's Date: 2019-06-29
State: IA
County: Buena_Vista
Facility Name: Buena Vista Co. Jail
State Code: 16
Jail ID: 942

Executing scrape...
Traceback (most recent call last):
File "Buena_Vista.py", line 141, in 
scraper.run()
File "/usr/jdi/prod-jdi/_Generic_Classes/SuperScraper.py", line 407, in run
self.format_and_save()
File "/usr/jdi/prod-jdi/_Generic_Classes/SuperScraper.py", line 341, in format_and_save
out['Name'] = out['Name'].apply(lambda x: self.name_reformat(x))
File "/usr/local/lib64/python3.6/site-packages/pandas/core/series.py", line 3591, in apply
mapped = lib.map_infer(values, f, convert=convert_dtype)
File "pandas/_libs/lib.pyx", line 2217, in pandas._libs.lib.map_infer
File "/usr/jdi/prod-jdi/_Generic_Classes/SuperScraper.py", line 341, in 
out['Name'] = out['Name'].apply(lambda x: self.name_reformat(x))
File "/usr/jdi/prod-jdi/_Generic_Classes/SuperScraper.py", line 60, in name_reformat
last, first = row.split(',')
ValueError: too many values to unpack (expected 2)

**Comment by public-safety-lab** [comment]
Bug Currently in prod-jdi
